augmentation_params:
  upsample_crop: 32
  batch_crop_frac: 0.05

training_params:
  epochs: 5
  validation_interval: None
  train_log_interval: 100
  batch_size: 64
  warmup_frac: 0.05

mask_threshold: 0.85
mask_inflation: 1.
mask_pct_max: 0.6

optimizer_params:
  lr: 0.00002
  weight_decay: 0.01
  betas: [0.9, 0.98]

bending_college_args:
  mask_rate: 0.065
  # mask_span: 5
  layer_drop: 0.01
  multi_gpu: False
  temp: 0.1
  encoder_grad_frac: 0.1
  num_negatives: 20
  enc_feat_l2: 1.0
  enc_downsample: [3, 2] # testare se cpu dipende da questo o mask_span
  enc_width: [3, 2]

dataset:
  in_channels: 128
  data_len: 1026 # minumum length of the dataset
  load_preprocessed: True
  redo_preprocessing: False